# Generated by Django 5.1.4 on 2025-03-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='mood_value',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='gratitude',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moodentry',
            name='mood',
            field=models.CharField(choices=[('Happy', 5), ('Calm', 4), ('Neutral', 3), ('Anxious', 2), ('Sad', 1)], max_length=20),
        ),
    ]
