# Generated by Django 5.1.4 on 2025-03-07 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_moodentry_mood_value_alter_moodentry_gratitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='mood_value',
            field=models.IntegerField(default=3),
        ),
    ]
