# Generated by Django 5.1.4 on 2025-03-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_wellnessplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wellnessplan',
            old_name='recommendations',
            new_name='daily_routine',
        ),
        migrations.AddField(
            model_name='wellnessplan',
            name='diet_tips',
            field=models.TextField(default='Stay hydrated and eat nutritious foods 🥗'),
        ),
        migrations.AddField(
            model_name='wellnessplan',
            name='relaxation_activities',
            field=models.TextField(default='Eat a balanced diet rich in whole foods 🥗'),
            preserve_default=False,
        ),
    ]
